spring.application.name=DichVuChuyenNha


spring.datasource.url=jdbc:mysql://localhost:3306/moving_service_db_official?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.mvc.pathmatch.matching-strategy=ant_path_matcher


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.web.resources.static-locations=classpath:/static/,file:uploads/


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password  # App password từ Google
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


server.port=8080

spring.ai.openai.api-key=AIzaSyBWmc6TDVCBLgP0p-qslst2yhxGSfn094A
spring.ai.openai.chat.base-url=https://generativelanguage.googleapis.com
spring.ai.openai.chat.completions-path=/v1beta/openai/chat/completions
spring.ai.openai.chat.options.model=gemini-2.0-flash

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/oauth2/jwks
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/oauth2/jwks
spring.security.oauth2.resourceserver.jwt.secret=${jwt.secret}


jwt.secret=ab6dffa546fadea384900784fa96d40e
jwt.signerKey=qCicH6xgjm6rXWmaejnA2PB//lmJP5lKBCsW6pPKOW5/Y8oR5LNl35+qYSDhFIR0

jwt.refresh-token.expiration=604800000
jwt.expirationSec=3600
# Cho ph�p multipart upload
spring.servlet.multipart.enabled=true

# Gi?i h?n dung l??ng file upload (? ?�y cho ph�p t?i 10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

payos.clientId=9ad82cc1-1c50-48c1-a3bd-d55de27f6ad5
payos.apiKey=92dd2abf-c265-48b8-8bdb-7fb8bc97704b
payos.checksumKey=0c5d9e27287a2a4ee84e83368ec32f0aa6e09fb320c18ab2b215b32cd77f3d1e
payos.api-url=https://api-merchant.payos.vn/v2/payment-requests
